---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: amitkshirsagar13/shinigami
        imagePullPolicy: IfNotPresent
        env:
        - name: VPORT
          value: "8987"
        ports:
        - containerPort: 8987
---
apiVersion: v1
kind: Service
metadata:
   name: demo-service
spec:
   selector:
      app: demo
   ports:
   - port: 8987
     name: demo-port
     targetPort: 8987
     nodePort: 30987
   type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/master/docker-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
